apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db.fullname" . }}-init-scripts
  labels:
    {{- include "db.labels" . | nindent 4 }}
data:
  # 01-init-database.sql - 데이터베이스 초기화
  "01-init-database.sql": |
    -- 데이터베이스 생성 (이미 존재하면 무시)
    CREATE DATABASE IF NOT EXISTS {{ .Values.env.MYSQL_DATABASE }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- 사용자 권한 설정
    GRANT ALL PRIVILEGES ON {{ .Values.env.MYSQL_DATABASE }}.* TO '{{ .Values.env.MYSQL_USER }}'@'%';
    FLUSH PRIVILEGES;

    -- 데이터베이스 선택
    USE {{ .Values.env.MYSQL_DATABASE }};

  # 02-create-tables.sql - 테이블 생성
  "02-create-tables.sql": |
    USE {{ .Values.env.MYSQL_DATABASE }};

    -- 사용자 테이블
    CREATE TABLE IF NOT EXISTS users (
      id VARCHAR(36) PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      password VARCHAR(255) NOT NULL,
      name VARCHAR(100) NOT NULL,
      phone VARCHAR(20),
      role ENUM('user', 'admin', 'business') DEFAULT 'user',
      profileImage VARCHAR(500),
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deletedAt TIMESTAMP NULL
    );

    -- 식당 테이블
    CREATE TABLE IF NOT EXISTS restaurants (
      id VARCHAR(36) PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      nameKorean VARCHAR(255) NOT NULL,
      address TEXT NOT NULL,
      phone VARCHAR(20),
      category VARCHAR(100),
      description TEXT,
      lat DECIMAL(10, 8),
      lng DECIMAL(11, 8),
      image VARCHAR(500),
      tags JSON,
      openingHours JSON,
      services JSON,
      social JSON,
      michelinGuide VARCHAR(255),
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deletedAt TIMESTAMP NULL
    );

    -- 메뉴 아이템 테이블
    CREATE TABLE IF NOT EXISTS menu_items (
      id VARCHAR(36) PRIMARY KEY,
      restaurantId VARCHAR(36) NOT NULL,
      name VARCHAR(255) NOT NULL,
      price DECIMAL(10, 2) NOT NULL,
      description TEXT,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
    );

    -- 예약 테이블
    CREATE TABLE IF NOT EXISTS reservations (
      id VARCHAR(36) PRIMARY KEY,
      userId VARCHAR(36) NOT NULL,
      restaurantId VARCHAR(36) NOT NULL,
      reservationDate DATE NOT NULL,
      reservationTime TIME NOT NULL,
      partySize INT NOT NULL,
      status ENUM('pending', 'confirmed', 'cancelled', 'completed') DEFAULT 'pending',
      specialRequests TEXT,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deletedAt TIMESTAMP NULL,
      FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
    );

    -- 리뷰 테이블
    CREATE TABLE IF NOT EXISTS reviews (
      id VARCHAR(36) PRIMARY KEY,
      userId VARCHAR(36) NOT NULL,
      restaurantId VARCHAR(36) NOT NULL,
      rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
      comment TEXT,
      images JSON,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deletedAt TIMESTAMP NULL,
      FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
    );

    -- 즐겨찾기 테이블
    CREATE TABLE IF NOT EXISTS favorites (
      id VARCHAR(36) PRIMARY KEY,
      userId VARCHAR(36) NOT NULL,
      restaurantId VARCHAR(36) NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE KEY unique_user_restaurant (userId, restaurantId),
      FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
    );

    -- 결제 테이블
    CREATE TABLE IF NOT EXISTS payments (
      id VARCHAR(36) PRIMARY KEY,
      reservationId VARCHAR(36) NOT NULL,
      amount DECIMAL(10, 2) NOT NULL,
      status ENUM('pending', 'completed', 'failed', 'refunded') DEFAULT 'pending',
      paymentMethod VARCHAR(50),
      transactionId VARCHAR(255),
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (reservationId) REFERENCES reservations(id) ON DELETE CASCADE
    );

    -- VIP 요청 테이블
    CREATE TABLE IF NOT EXISTS vip_requests (
      id VARCHAR(36) PRIMARY KEY,
      userId VARCHAR(36) NOT NULL,
      restaurantId VARCHAR(36) NOT NULL,
      requestDate DATE NOT NULL,
      requestTime TIME NOT NULL,
      partySize INT NOT NULL,
      specialRequests TEXT,
      status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
      adminNotes TEXT,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (restaurantId) REFERENCES restaurants(id) ON DELETE CASCADE
    );

    -- 알림 설정 테이블
    CREATE TABLE IF NOT EXISTS notification_settings (
      id VARCHAR(36) PRIMARY KEY,
      userId VARCHAR(36) NOT NULL,
      emailNotifications BOOLEAN DEFAULT TRUE,
      pushNotifications BOOLEAN DEFAULT TRUE,
      smsNotifications BOOLEAN DEFAULT FALSE,
      reservationReminders BOOLEAN DEFAULT TRUE,
      marketingEmails BOOLEAN DEFAULT FALSE,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
    );

  # 03-seed-data.sql - 초기 데이터 삽입
  "03-seed-data.sql": |
    USE {{ .Values.env.MYSQL_DATABASE }};

    -- 관리자 사용자 생성
    INSERT IGNORE INTO users (id, email, password, name, role) VALUES
    ('admin-001', 'admin@michelin.com', '$2b$10$rQZ8K9mN2pL1vX3yA6bC7dE8fG9hI0jK1lM2nO3pQ4rS5tU6vW7xY8zA9bC0dE1f', '관리자', 'admin');

    -- 테스트 사용자 생성
    INSERT IGNORE INTO users (id, email, password, name, role) VALUES
    ('user-001', 'user@test.com', '$2b$10$rQZ8K9mN2pL1vX3yA6bC7dE8fG9hI0jK1lM2nO3pQ4rS5tU6vW7xY8zA9bC0dE1f', '테스트 사용자', 'user'),
    ('business-001', 'business@test.com', '$2b$10$rQZ8K9mN2pL1vX3yA6bC7dE8fG9hI0jK1lM2nO3pQ4rS5tU6vW7xY8zA9bC0dE1f', '비즈니스 사용자', 'business');

    -- 알림 설정 생성
    INSERT IGNORE INTO notification_settings (id, userId, emailNotifications, pushNotifications, smsNotifications, reservationReminders, marketingEmails) VALUES
    ('notif-001', 'user-001', TRUE, TRUE, FALSE, TRUE, FALSE),
    ('notif-002', 'business-001', TRUE, TRUE, TRUE, TRUE, TRUE);

  # 04-seed-restaurants.sql - 식당 데이터 삽입
  "04-seed-restaurants.sql": |
    USE {{ .Values.env.MYSQL_DATABASE }};

    -- 식당 데이터 삽입
    INSERT IGNORE INTO restaurants (id, name, nameKorean, address, phone, category, description, lat, lng, image, tags, openingHours, services, social, michelinGuide) VALUES
    ('1', 'Seokyonanmyunbang', '서교난면방', '서울특별시 마포구 동교로 12길, 16', '0507-1487-0943', '미쉐린 빕구르망', '이탈리안 퀴진 전문 셰프로서 견실한 시간을 보내온 김낙영 셰프의 개성 있는 면 요리 레스토랑 서교난면방. 파스타와 라자냐를 전문적으로 다루던 셰프의 손에서 나온 난면은 그의 경험과 아이디어가 녹아든 한국적이면서도 이탤리언 퀴진의 감성과 터치가 가미된 독창적인 맛의 즐거움을 준다.', 37.55359, 126.91231, 'https://axwwgrkdco.cloudimg.io/v7/__gmpics3__/7c16ff62981841b897d6bf7bab626165.jpeg?w=700&h=700&org_if_sml=1', '["서울 합정", "국수"]', '{"regular": "11:00 ~ 21:00", "dayOff": "휴무일 없음", "breakTime": "브레이크 타임 15:00 ~ 17:30", "lastOrder": "라스트 오더 20:30"}', '["대관 가능", "예약금 0원 결제"]', '{"webpage": "", "instagram": ""}', '미쉐린 가이드 서울 2025'),

    ('2', 'Woo-lae-oak', '우래옥', '서울특별시 중구 창경궁로 65-29', '02-2265-0151', '미쉐린 빕구르망', '서울 시내 최고의 평양식 냉면 전문점 중 하나로 손꼽히는 우래옥은 1946년 개업한 이래 꾸준히 전통을 이어오고 있는 유서 깊은 레스토랑이다. 이 집의 대표 메뉴는 전통 평양냉면과 불고기. 오랜 세월에 걸쳐 습득한 노하우와 국내산 재료만을 사용하는 뚝심으로 한결같은 맛을 자랑하는 냉면과 고품질의 한우를 제공한다.', 37.5701653, 126.9997218, 'https://axwwgrkdco.cloudimg.io/v7/__gmpics3__/b9f21cbd44d340bda27994534abddebf.jpeg?w=700&h=700&org_if_sml=1', '["서울 을지로", "냉면"]', '{"regular": "11:30 ~ 21:00", "dayOff": "휴무일 매주 월요일", "breakTime": "브레이크 타임 없음", "lastOrder": "라스트 오더 20:40"}', '["주차 시설", "발렛 서비스", "무선 인터넷"]', '{"webpage": "", "instagram": ""}', '미쉐린 가이드 서울 2025'),

    ('3', 'Buchon-yukhoe', '부촌육회', '서울특별시 종로구 종로 200-12', '02-2267-1831', '미쉐린 빕구르망', '국내 최초 사설 시장인 광장시장의 육회 골목 한편에 자리 잡고 있는 부촌육회. 1965년에 부촌 식당으로 개업한 이곳은 1980년대부터 갈비탕과 함께 전라도식 육회를 조금씩 선보이기 시작했다. 고추장 양념에 버무리는 전라도식 육회를 참기름과 배를 넣은 서울식 육회로 바꾼 이유는 손님들의 입맛에 맞추기 위해서다.', 37.5688182, 127.0009995, 'https://axwwgrkdco.cloudimg.io/v7/__gmpics3__/3d7a4be5676c4d3ba4a2bae65d8557cb.jpeg?w=400&h=400&org_if_sml=1', '["서울 종로", "육류", "고기요리"]', '{"regular": "10:00 ~ 21:30", "dayOff": "휴무일 없음", "breakTime": "브레이크 타임 없음", "lastOrder": "라스트 오더 21:00"}', '["포장", "무선인터넷"]', '{"webpage": "http://bcyukhoe.modoo.at/", "instagram": ""}', '미쉐린 가이드 서울 2025'),

    ('4', 'Pildongmyeonok', '필동면옥', '서울특별시 중구 서애로 26', '02-2266-2611', '미쉐린 빕구르망', '중구 필동에 자리하고 있는 남산골 한옥마을 인근의 평양냉면 레스토랑. 내로라하는 평양냉면 전문점 중 하나인 필동면옥은 오랜 세월 많은 이들에게 사랑받아왔다. 자칫 특징 없이 밍밍하다고 느낄 수 있을 만큼 깔끔한 맛을 자랑하는 이곳 육수에서 나는 섬세한 육 향과 은은한 감칠맛에 중독되어 단골이 된 손님들도 많다고.', 37.5688182, 126.9997218, 'https://axwwgrkdco.cloudimg.io/v7/__gmpics3__/example-image.jpeg?w=400&h=400&org_if_sml=1', '["서울 충무로", "국수", "냉면"]', '{"regular": "11:00 ~ 20:30", "dayOff": "휴무일 매주 일요일", "breakTime": "브레이크 타임 16:00~17:00", "lastOrder": "라스트 오더 21:00"}', '["주차시설"]', '{"webpage": "", "instagram": ""}', '미쉐린 가이드 서울 2025'),

    ('5', 'Jungsik', '정식당', '서울특별시 강남구 선릉로 158길 11', '02-517-4654', '미쉐린 스타', '한국 요리의 현대적 재해석을 통해 세계적인 주목을 받고 있는 정식당. 전통 한국 요리의 맛과 정신을 유지하면서도 현대적인 감각과 기법을 접목시켜 독창적인 퓨전 요리를 선보인다. 미쉐린 가이드에서 스타를 받은 이곳은 한국 요리의 새로운 가능성을 보여주는 대표적인 레스토랑이다.', 37.5275, 127.0275, 'https://axwwgrkdco.cloudimg.io/v7/__gmpics3__/jungsik-example.jpeg?w=700&h=700&org_if_sml=1', '["서울 강남", "퓨전", "한식"]', '{"regular": "12:00 ~ 22:00", "dayOff": "휴무일 매주 월요일", "breakTime": "브레이크 타임 15:00~17:00", "lastOrder": "라스트 오더 21:00"}', '["발렛 서비스", "와인 페어링", "셰프 테이블"]', '{"webpage": "https://jungsik.kr", "instagram": "@jungsik_seoul"}', '미쉐린 가이드 서울 2025');

    -- 메뉴 아이템 데이터 삽입
    INSERT IGNORE INTO menu_items (id, restaurantId, name, price, description) VALUES
    -- 서교난면방 메뉴
    ('menu-1-1', '1', '서교메밀냉난면', 15000, '메밀과 난면을 조합한 시원한 냉면'),
    ('menu-1-2', '1', '한우설렁탕 난면', 12000, '한우 육수로 만든 깊은 맛의 난면'),
    ('menu-1-3', '1', '한우난면', 13000, '프리미엄 한우로 만든 난면'),
    ('menu-1-4', '1', '구엄닭난면(런치only)', 10000, '구엄닭 육수로 만든 런치 전용 메뉴'),
    ('menu-1-5', '1', '서교난면', 12000, '시그니처 메뉴인 서교 스타일 난면'),

    -- 우래옥 메뉴
    ('menu-2-1', '2', '평양냉면', 16000, '전통 평양식 냉면'),
    ('menu-2-2', '2', '비빔냉면', 16000, '매콤달콤한 비빔냉면'),
    ('menu-2-3', '2', '온면', 16000, '따뜻한 온면'),
    ('menu-2-4', '2', '김치말이 냉면', 16000, '김치말이를 곁들인 냉면'),

    -- 부촌육회 메뉴
    ('menu-3-1', '3', '육회비빔밥', 18000, '신선한 육회와 비빔밥'),
    ('menu-3-2', '3', '육회', 28000, '프리미엄 육회'),
    ('menu-3-3', '3', '육회국수', 18000, '육회를 곁들인 국수'),

    -- 필동면옥 메뉴
    ('menu-4-1', '4', '냉면', 15000, '전통 평양냉면'),
    ('menu-4-2', '4', '온면', 15000, '따뜻한 온면'),
    ('menu-4-3', '4', '수육', 20000, '두툼하고 부드러운 돼지 수육'),

    -- 정식당 메뉴
    ('menu-5-1', '5', '정식당 시그니처 코스', 180000, '셰프가 선별한 시그니처 코스'),
    ('menu-5-2', '5', '런치 코스', 120000, '점심 시간 전용 코스'),
    ('menu-5-3', '5', '디너 코스', 220000, '저녁 시간 전용 프리미엄 코스');

  # 05-mark-initialized.sql - 초기화 완료 표시
  "05-mark-initialized.sql": |
    USE {{ .Values.env.MYSQL_DATABASE }};

    -- 초기화 완료 테이블 생성
    CREATE TABLE IF NOT EXISTS db_initialization (
      id INT PRIMARY KEY AUTO_INCREMENT,
      initialized_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      version VARCHAR(50) DEFAULT '1.0.0'
    );

    -- 초기화 완료 표시
    INSERT IGNORE INTO db_initialization (id, version) VALUES (1, '1.0.0');