apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
  # 기타 환경변수 추가 가능