apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  # 기타 시크릿 추가 가능