version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/michelin-backend:latest
    container_name: michelin-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - michelin-network

  frontend:
    image: ${DOCKERHUB_USERNAME}/michelin-frontend:latest
    container_name: michelin-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - michelin-network

  redis:
    image: redis:alpine
    container_name: michelin-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - michelin-network

networks:
  michelin-network:
    driver: bridge

volumes:
  redis-data: 