// 표준 응답 코드 상수 정의
const RESPONSE_CODES = {
    // 성공 코드
    SUCCESS: {
        // 사용자 관련
        USER_LOGIN: 'SUCCESS_USER_LOGIN',
        USER_LOGOUT: 'SUCCESS_USER_LOGOUT',
        USER_REGISTER: 'SUCCESS_USER_REGISTER',
        USER_PROFILE_UPDATE: 'SUCCESS_USER_PROFILE_UPDATE',
        USER_PROFILE_GET: 'SUCCESS_USER_PROFILE_GET',

        // 레스토랑 관련
        RESTAURANT_CREATED: 'SUCCESS_RESTAURANT_CREATED',
        RESTAURANT_UPDATED: 'SUCCESS_RESTAURANT_UPDATED',
        RESTAURANT_DELETED: 'SUCCESS_RESTAURANT_DELETED',
        RESTAURANT_LIST_GET: 'SUCCESS_RESTAURANT_LIST_GET',
        RESTAURANT_DETAIL_GET: 'SUCCESS_RESTAURANT_DETAIL_GET',

        // 예약 관련
        RESERVATION_CREATED: 'SUCCESS_RESERVATION_CREATED',
        RESERVATION_UPDATED: 'SUCCESS_RESERVATION_UPDATED',
        RESERVATION_CANCELLED: 'SUCCESS_RESERVATION_CANCELLED',
        RESERVATION_LIST_GET: 'SUCCESS_RESERVATION_LIST_GET',
        RESERVATION_DETAIL_GET: 'SUCCESS_RESERVATION_DETAIL_GET',

        // 리뷰 관련
        REVIEW_CREATED: 'SUCCESS_REVIEW_CREATED',
        REVIEW_UPDATED: 'SUCCESS_REVIEW_UPDATED',
        REVIEW_DELETED: 'SUCCESS_REVIEW_DELETED',
        REVIEW_LIST_GET: 'SUCCESS_REVIEW_LIST_GET',

        // 즐겨찾기 관련
        FAVORITE_ADDED: 'SUCCESS_FAVORITE_ADDED',
        FAVORITE_REMOVED: 'SUCCESS_FAVORITE_REMOVED',
        FAVORITE_LIST_GET: 'SUCCESS_FAVORITE_LIST_GET',

        // 사업자 관련
        BUSINESS_APPLIED: 'SUCCESS_BUSINESS_APPLIED',
        BUSINESS_STATUS_GET: 'SUCCESS_BUSINESS_STATUS_GET',
        BUSINESS_SETTINGS_GET: 'SUCCESS_BUSINESS_SETTINGS_GET',
        BUSINESS_SETTINGS_UPDATED: 'SUCCESS_BUSINESS_SETTINGS_UPDATED',

        // VIP 요청 관련
        VIP_REQUEST_CREATED: 'SUCCESS_VIP_REQUEST_CREATED',
        VIP_REQUEST_LIST_GET: 'SUCCESS_VIP_REQUEST_LIST_GET',
        VIP_REQUEST_UPDATED: 'SUCCESS_VIP_REQUEST_UPDATED',

        // 결제 관련
        PAYMENT_CREATED: 'SUCCESS_PAYMENT_CREATED',
        PAYMENT_COMPLETED: 'SUCCESS_PAYMENT_COMPLETED',
        PAYMENT_LIST_GET: 'SUCCESS_PAYMENT_LIST_GET',

        // 관리자 관련
        ADMIN_STATS_GET: 'SUCCESS_ADMIN_STATS_GET',
        ADMIN_RESERVATION_LIST_GET: 'SUCCESS_ADMIN_RESERVATION_LIST_GET',
        ADMIN_USER_LIST_GET: 'SUCCESS_ADMIN_USER_LIST_GET',
        ADMIN_RESTAURANT_LIST_GET: 'SUCCESS_ADMIN_RESTAURANT_LIST_GET',
        ADMIN_VIP_REQUEST_LIST_GET: 'SUCCESS_ADMIN_VIP_REQUEST_LIST_GET',
        ADMIN_VIP_REQUEST_APPROVED: 'SUCCESS_ADMIN_VIP_REQUEST_APPROVED',
        ADMIN_VIP_REQUEST_REJECTED: 'SUCCESS_ADMIN_VIP_REQUEST_REJECTED',
        ADMIN_BUSINESS_APPROVED: 'SUCCESS_ADMIN_BUSINESS_APPROVED',
        ADMIN_BUSINESS_REJECTED: 'SUCCESS_ADMIN_BUSINESS_REJECTED',

        // 일반
        DATA_RETRIEVED: 'SUCCESS_DATA_RETRIEVED',
        OPERATION_COMPLETED: 'SUCCESS_OPERATION_COMPLETED'
    },

    // 오류 코드
    ERROR: {
        // 인증 관련
        UNAUTHORIZED: 'ERROR_UNAUTHORIZED',
        FORBIDDEN: 'ERROR_FORBIDDEN',
        TOKEN_EXPIRED: 'ERROR_TOKEN_EXPIRED',
        INVALID_CREDENTIALS: 'ERROR_INVALID_CREDENTIALS',

        // 유효성 검사 관련
        VALIDATION_FAILED: 'ERROR_VALIDATION_FAILED',
        MISSING_REQUIRED_FIELDS: 'ERROR_MISSING_REQUIRED_FIELDS',
        INVALID_FORMAT: 'ERROR_INVALID_FORMAT',

        // 리소스 관련
        RESOURCE_NOT_FOUND: 'ERROR_RESOURCE_NOT_FOUND',
        RESOURCE_ALREADY_EXISTS: 'ERROR_RESOURCE_ALREADY_EXISTS',
        RESOURCE_CONFLICT: 'ERROR_RESOURCE_CONFLICT',

        // 비즈니스 로직 관련
        RESERVATION_CONFLICT: 'ERROR_RESERVATION_CONFLICT',
        INSUFFICIENT_PERMISSIONS: 'ERROR_INSUFFICIENT_PERMISSIONS',
        BUSINESS_NOT_APPROVED: 'ERROR_BUSINESS_NOT_APPROVED',

        // 서버 관련
        INTERNAL_SERVER_ERROR: 'ERROR_INTERNAL_SERVER_ERROR',
        DATABASE_ERROR: 'ERROR_DATABASE_ERROR',
        EXTERNAL_SERVICE_ERROR: 'ERROR_EXTERNAL_SERVICE_ERROR',

        // 요청 관련
        RATE_LIMIT_EXCEEDED: 'ERROR_RATE_LIMIT_EXCEEDED',
        INVALID_REQUEST: 'ERROR_INVALID_REQUEST',
        PAYMENT_FAILED: 'ERROR_PAYMENT_FAILED'
    }
};

module.exports = RESPONSE_CODES;