# 프로덕션 환경용 모니터링 설정

replicaCount: 2

# Prometheus 설정
prometheus:
  enabled: true
  persistence:
    enabled: true
    size: 50Gi
    storageClass: ""
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Grafana 설정
grafana:
  enabled: true
  adminPassword: "{{ .Values.grafana.adminPassword }}"  # Secret에서 주입
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi

# Loki 설정
loki:
  enabled: true
  persistence:
    enabled: true
    size: 100Gi
    storageClass: ""
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Promtail 설정
promtail:
  enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

# Ingress 설정
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: monitoring.michelin.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: monitoring-tls
      hosts:
        - monitoring.michelin.com

# Alertmanager 설정 (프로덕션에서는 활성화)
alertmanager:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/your/slack/webhook'
    route:
      receiver: 'slack-notifications'
      group_by: ['alertname', 'job']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#michelin-alerts'
            send_resolved: true
            title: '{{ .CommonAnnotations.summary }}'
            text: '{{ .CommonAnnotations.description }}'