# 개발 환경용 values
replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "8.0"

# Init Container 설정
initContainer:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

env:
  MYSQL_DATABASE: michelin_dev
  MYSQL_USER: michelin_user

secrets:
  MYSQL_ROOT_PASSWORD: "dev_password_0426"
  MYSQL_PASSWORD: "dev_password_0426"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

livenessProbe:
  tcpSocket:
    port: 3306
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 3306
  initialDelaySeconds: 10
  periodSeconds: 10

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""