apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  VITE_API_URL: {{ .Values.env.VITE_API_URL | quote }}
  # 기타 환경변수 추가 가능