{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      component: grafana
  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        component: grafana
    spec:
      serviceAccountName: {{ include "monitoring.serviceAccountName" . }}
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel,grafana-worldmap-panel"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-alert-rules
              mountPath: /etc/grafana/provisioning/alerting/alert-rules.yaml
              subPath: alert-rules.yaml
            - name: grafana-alert-notification
              mountPath: /etc/grafana/provisioning/alerting/notification-channels.yaml
              subPath: notification-channels.yaml
            - name: grafana-alert-provisioning
              mountPath: /etc/grafana/provisioning/alerting/alerting.yaml
              subPath: alerting.yaml
      volumes:
        {{- if .Values.grafana.persistence.enabled }}
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ include "monitoring.fullname" . }}-grafana
        {{- else }}
        - name: grafana-storage
          emptyDir: {}
        {{- end }}
        - name: grafana-datasources
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-datasources
        - name: grafana-dashboard
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-dashboard
        - name: grafana-dashboard-provisioning
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-dashboard-provisioning
        - name: grafana-alert-rules
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-alert-rules
        - name: grafana-alert-notification
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-alert-notification
        - name: grafana-alert-provisioning
          configMap:
            name: {{ include "monitoring.fullname" . }}-grafana-alert-provisioning
{{- end }}