apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-alert-rules
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  alert-rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: michelin-alerts
        folder: "Michelin"
        interval: 1m
        rules:
          - uid: "reservation-latency"
            title: "Reservation API P95 Latency High"
            condition: "C"
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: "Prometheus"
                model:
                  expr: "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{route=\"/api/reservation\"}[5m]))"
                  intervalMs: 60000
                  maxDataPoints: 43200
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: "Prometheus"
                model:
                  expr: "1"
                  intervalMs: 60000
                  maxDataPoints: 43200
            noDataState: "NoData"
            execErrState: "Error"
            for: 5m
            annotations:
              summary: "예약 API P95 지연 시간 2초 초과"
            labels:
              severity: "critical"
            notifications:
              - uid: "slack-main"
            isPaused: false
          - uid: "error-rate"
            title: "전체 에러율 5% 초과"
            condition: "C"
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: "Prometheus"
                model:
                  expr: "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100"
                  intervalMs: 60000
                  maxDataPoints: 43200
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: "Prometheus"
                model:
                  expr: "5"
                  intervalMs: 60000
                  maxDataPoints: 43200
            noDataState: "NoData"
            execErrState: "Error"
            for: 2m
            annotations:
              summary: "전체 에러율 5% 초과"
            labels:
              severity: "critical"
            notifications:
              - uid: "slack-main"
            isPaused: false