{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-loki
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    component: loki
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    component: loki
{{- end }}