{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitoring.fullname" . }}-cluster-role
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "monitoring.fullname" . }}-cluster-role-binding
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "monitoring.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "monitoring.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}